"""Component metadata for legacy pages plugin."""

from typing import TypedDict


class LegacyPageDefinition(TypedDict, total=False):
    """Typed metadata for legacy pages."""

    id: str
    label: str
    icon: str
    section: str
    group: str
    order: int
    group_order: int
    description: str


LEGACY_PAGE_DEFINITIONS: list[LegacyPageDefinition] = [
    # Data pages
    {
        "id": "manage",
        "label": "Manage",
        "icon": "carbon:data-table",
        "section": "Data",
        "order": 1,
    },
    {
        "id": "view",
        "label": "View",
        "icon": "carbon:view",
        "section": "Data",
        "order": 2,
    },
    {
        "id": "explore",
        "label": "Explore",
        "icon": "carbon:explore",
        "section": "Data",
        "order": 3,
    },
    {
        "id": "transform",
        "label": "Transform",
        "icon": "carbon:settings-adjust",
        "section": "Data",
        "order": 4,
    },
    {
        "id": "visualize",
        "label": "Visualize",
        "icon": "carbon:chart-scatter",
        "section": "Data",
        "order": 5,
    },
    {
        "id": "pivot",
        "label": "Pivot",
        "icon": "carbon:data-reference",
        "section": "Data",
        "order": 6,
    },
    {
        "id": "combine",
        "label": "Combine",
        "icon": "carbon:data-connected",
        "section": "Data",
        "order": 7,
    },
    {
        "id": "report",
        "label": "Report",
        "icon": "carbon:document",
        "section": "Data",
        "order": 8,
    },
    {
        "id": "sql-query",
        "label": "SQL Query",
        "icon": "carbon:data-base",
        "section": "Data",
        "order": 9,
    },
    # Basics pages
    {
        "id": "single-mean",
        "label": "Single Mean",
        "icon": "carbon:chart-average",
        "section": "Basics",
        "group": "Means",
        "order": 1,
        "group_order": 1,
    },
    {
        "id": "compare-means",
        "label": "Compare Means",
        "icon": "carbon:compare",
        "section": "Basics",
        "group": "Means",
        "order": 2,
        "group_order": 1,
    },
    {
        "id": "single-prop",
        "label": "Single Proportion",
        "icon": "carbon:percentage",
        "section": "Basics",
        "group": "Proportions",
        "order": 1,
        "group_order": 2,
    },
    {
        "id": "compare-props",
        "label": "Compare Proportions",
        "icon": "carbon:percentage",
        "section": "Basics",
        "group": "Proportions",
        "order": 2,
        "group_order": 2,
    },
    {
        "id": "cross-tabs",
        "label": "Cross Tabs",
        "icon": "carbon:table-split",
        "section": "Basics",
        "group": "Tables",
        "order": 1,
        "group_order": 3,
    },
    {
        "id": "goodness",
        "label": "Goodness of Fit",
        "icon": "carbon:fit-to-screen",
        "section": "Basics",
        "group": "Tables",
        "order": 2,
        "group_order": 3,
    },
    {
        "id": "correlation",
        "label": "Correlation",
        "icon": "carbon:connection-signal",
        "section": "Basics",
        "group": "Other",
        "order": 1,
        "group_order": 4,
    },
    {
        "id": "clt",
        "label": "CLT",
        "icon": "carbon:chart-line-data",
        "section": "Basics",
        "group": "Other",
        "order": 2,
        "group_order": 4,
    },
    {
        "id": "prob-calc",
        "label": "Probability Calc",
        "icon": "carbon:calculator-check",
        "section": "Basics",
        "group": "Other",
        "order": 3,
        "group_order": 4,
    },
    # Design pages
    {
        "id": "doe",
        "label": "DOE",
        "icon": "carbon:chemistry",
        "section": "Design",
        "order": 1,
    },
    {
        "id": "sampling",
        "label": "Sampling",
        "icon": "carbon:diagram-reference",
        "section": "Design",
        "order": 2,
    },
    {
        "id": "sample_size",
        "label": "Sample Size",
        "icon": "carbon:calculator",
        "section": "Design",
        "order": 3,
    },
    {
        "id": "sample_size_comp",
        "label": "Sample Size Comparison",
        "icon": "carbon:comparison",
        "section": "Design",
        "order": 4,
    },
    {
        "id": "randomizer",
        "label": "Randomizer",
        "icon": "carbon:shuffle",
        "section": "Design",
        "order": 5,
    },
    # Model pages
    {
        "id": "linear-regression",
        "label": "Linear Regression",
        "icon": "carbon:chart-line",
        "section": "Model",
        "group": "Estimate",
        "order": 1,
        "group_order": 1,
    },
    {
        "id": "logistic-regression",
        "label": "Logistic Regression",
        "icon": "carbon:operations-record",
        "section": "Model",
        "group": "Estimate",
        "order": 2,
        "group_order": 1,
    },
    {
        "id": "multinomial-logit",
        "label": "Multinomial Logit",
        "icon": "carbon:flow",
        "section": "Model",
        "group": "Estimate",
        "order": 3,
        "group_order": 1,
    },
    {
        "id": "naive-bayes",
        "label": "Naive Bayes",
        "icon": "carbon:calculation",
        "section": "Model",
        "group": "Estimate",
        "order": 4,
        "group_order": 1,
    },
    {
        "id": "neural-network",
        "label": "Neural Network",
        "icon": "carbon:network-3",
        "section": "Model",
        "group": "Estimate",
        "order": 5,
        "group_order": 1,
    },
    {
        "id": "decision-tree",
        "label": "Decision Tree",
        "icon": "carbon:tree-view",
        "section": "Model",
        "group": "Trees",
        "order": 1,
        "group_order": 2,
    },
    {
        "id": "random-forest",
        "label": "Random Forest",
        "icon": "carbon:trees",
        "section": "Model",
        "group": "Trees",
        "order": 2,
        "group_order": 2,
    },
    {
        "id": "gradient-boosting",
        "label": "Gradient Boosting",
        "icon": "carbon:chart-stacked",
        "section": "Model",
        "group": "Trees",
        "order": 3,
        "group_order": 2,
    },
    {
        "id": "evaluate-regression",
        "label": "Evaluate Regression",
        "icon": "carbon:chart-evaluation",
        "section": "Model",
        "group": "Evaluate",
        "order": 1,
        "group_order": 3,
    },
    {
        "id": "evaluate-classification",
        "label": "Evaluate Classification",
        "icon": "carbon:chart-custom",
        "section": "Model",
        "group": "Evaluate",
        "order": 2,
        "group_order": 3,
    },
    {
        "id": "collaborative-filtering",
        "label": "Collaborative Filtering",
        "icon": "carbon:recommend",
        "section": "Model",
        "group": "Recommend & Decide",
        "order": 1,
        "group_order": 4,
    },
    {
        "id": "decision-analysis",
        "label": "Decision Analysis",
        "icon": "carbon:decision-tree",
        "section": "Model",
        "group": "Recommend & Decide",
        "order": 2,
        "group_order": 4,
    },
    {
        "id": "simulator",
        "label": "Simulate",
        "icon": "carbon:chart-scatter",
        "section": "Model",
        "group": "Recommend & Decide",
        "order": 3,
        "group_order": 4,
    },
    # Multivariate pages
    {
        "id": "pre-factor",
        "label": "Pre-Factor",
        "icon": "carbon:chart-radar",
        "section": "Multivariate",
        "order": 1,
    },
    {
        "id": "full-factor",
        "label": "Full Factor",
        "icon": "carbon:analytics-custom",
        "section": "Multivariate",
        "order": 2,
    },
    {
        "id": "kmeans-cluster",
        "label": "K-Means Clustering",
        "icon": "carbon:chart-cluster-bar",
        "section": "Multivariate",
        "order": 3,
    },
    {
        "id": "hierarchical-cluster",
        "label": "Hierarchical Clustering",
        "icon": "carbon:tree-view-alt",
        "section": "Multivariate",
        "order": 4,
    },
    {
        "id": "perceptual-map",
        "label": "Perceptual Map",
        "icon": "carbon:chart-bubble-packed",
        "section": "Multivariate",
        "order": 5,
    },
    {
        "id": "mds",
        "label": "MDS",
        "icon": "carbon:chart-3d",
        "section": "Multivariate",
        "order": 6,
    },
    {
        "id": "conjoint",
        "label": "Conjoint Analysis",
        "icon": "carbon:analytics",
        "section": "Multivariate",
        "order": 7,
    },
]
