#!/usr/bin/env python3
"""Fail when low-quality autogenerated docstring phrases are present."""

from __future__ import annotations

from pathlib import Path

BANNED_PHRASES = (
    "TODO: Describe parameter.",
    "TODO: Describe return value.",
    "Computed output produced by the function.",
    "Input value for this parameter.",
)

SEARCH_ROOTS = (Path("aiml_dash"), Path("tests"), Path("scripts"))
SELF_PATH = Path(__file__).resolve()


def iter_python_files() -> list[Path]:
    """Return all Python files under configured roots."""
    files: list[Path] = []
    for root in SEARCH_ROOTS:
        if root.exists():
            files.extend(sorted(root.rglob("*.py")))
    return [path for path in files if path.resolve() != SELF_PATH]


def main() -> int:
    """Run docstring quality checks and return shell exit code."""
    matches: list[str] = []
    for path in iter_python_files():
        try:
            text = path.read_text(encoding="utf-8")
        except OSError as exc:
            matches.append(f"{path}: unable to read file ({exc})")
            continue

        for line_no, line in enumerate(text.splitlines(), start=1):
            for phrase in BANNED_PHRASES:
                if phrase in line:
                    matches.append(
                        f"{path}:{line_no}: contains banned phrase: {phrase}"
                    )

    if matches:
        print("Docstring quality check failed:")
        for entry in matches:
            print(f"- {entry}")
        return 1

    print("Docstring quality check passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
